const array=[
    {
        "HotelKey": "3709697",
        "HotelName": null,
        "Image": null,
        "Countries": null,
        "Destination": null,
        "Amenities": null,
        "Location": null,
        "Price": 500.0,
        "Rating": "0.0",
        "BoardTypeId": "8",
        "BoardTypeCode": "1",
        "QuoteRef": null,
        "OutboundFlightDirect": "false",
        "InboundFlightDirect": "false",
        "OutboundDepartureDate": "2024-03-20T14:00:00",
        "OutboundArrivalDate": "2024-03-21T04:05:00",
        "OutboundDepartureAirportName": "Heathrow",
        "OutboundDepartureAirportCode": "LHR",
        "OutboundArrivalAirportName": "Abu Dhabi International",
        "OutboundArrivalAirportCode": "AUH",
        "OutboundLegCount": 1,
        "OutboundFlightDuration": 0,
        "OutboundFlightNumber": "MS778,MS916",
        "OutboundAirlineICAO": "MS",
        "InboundDepartureDate": "2024-03-22T05:05:00",
        "InboundArrivalDate": "2024-03-22T12:35:00",
        "InboundDepartureAirportName": "Abu Dhabi International",
        "InboundDepartureAirportCode": null,
        "InboundArrivalAirportName": "Heathrow",
        "InboundArrivalAirportCode": "LHR",
        "InboundLegCount": 1,
        "InboundFlightDuration": 0,
        "InboundFlightNumber": "MS917,MS777",
        "InboundAirlineICAO": "MS",
        "HolidayTypes": null,
        "Discount": null,
        "DiscountText": null,
        "CoupleRating": 0.0,
        "FamilyRating": 0.0,
        "TripAdvisorId": 0,
        "Resort": null,
        "HotelUrl": null,
        "HotelRating": null,
        "PostalCode": null,
        "CityName": null,
        "Latitude": null,
        "Longitude": null,
        "TripAdvisorRating": 0.0,
        "FreeCancellation": false,
        "HotelDescription": null,
        "Zoom": 0,
        "PayDeposit": false,
        "FromAirports": null,
        "Adult": null,
        "Child": null,
        "DateMin": null,
        "DateMax": null,
        "Duration": null,
        "BoardBasis": null,
        "SocialLinks": null
    },
    {
        "HotelKey": "3709697",
        "HotelName": null,
        "Image": null,
        "Countries": null,
        "Destination": null,
        "Amenities": null,
        "Location": null,
        "Price": 945.0,
        "Rating": "0.0",
        "BoardTypeId": "8",
        "BoardTypeCode": "1",
        "QuoteRef": null,
        "OutboundFlightDirect": "false",
        "InboundFlightDirect": "false",
        "OutboundDepartureDate": "2024-03-20T14:05:00",
        "OutboundArrivalDate": "2024-03-21T03:55:00",
        "OutboundDepartureAirportName": "London Gatwick Airport",
        "OutboundDepartureAirportCode": "LGW",
        "OutboundArrivalAirportName": "Abu Dhabi International",
        "OutboundArrivalAirportCode": "AUH",
        "OutboundLegCount": 1,
        "OutboundFlightDuration": 0,
        "OutboundFlightNumber": "QR5942,QR1040",
        "OutboundAirlineICAO": "BA,QR",
        "InboundDepartureDate": "2024-03-22T05:25:00",
        "InboundArrivalDate": "2024-03-22T12:35:00",
        "InboundDepartureAirportName": "Abu Dhabi International",
        "InboundDepartureAirportCode": null,
        "InboundArrivalAirportName": "London Gatwick Airport",
        "InboundArrivalAirportCode": "LGW",
        "InboundLegCount": 1,
        "InboundFlightDuration": 0,
        "InboundFlightNumber": "QR1041,QR327",
        "InboundAirlineICAO": "QR",
        "HolidayTypes": null,
        "Discount": null,
        "DiscountText": null,
        "CoupleRating": 0.0,
        "FamilyRating": 0.0,
        "TripAdvisorId": 0,
        "Resort": null,
        "HotelUrl": null,
        "HotelRating": null,
        "PostalCode": null,
        "CityName": null,
        "Latitude": null,
        "Longitude": null,
        "TripAdvisorRating": 0.0,
        "FreeCancellation": false,
        "HotelDescription": null,
        "Zoom": 0,
        "PayDeposit": false,
        "FromAirports": null,
        "Adult": null,
        "Child": null,
        "DateMin": null,
        "DateMax": null,
        "Duration": null,
        "BoardBasis": null,
        "SocialLinks": null
    },
    {
        "HotelKey": "7830025",
        "HotelName": null,
        "Image": null,
        "Countries": null,
        "Destination": null,
        "Amenities": null,
        "Location": null,
        "Price": 816.0,
        "Rating": "5",
        "BoardTypeId": "8",
        "BoardTypeCode": "1",
        "QuoteRef": null,
        "OutboundFlightDirect": "false",
        "InboundFlightDirect": "false",
        "OutboundDepartureDate": "2024-03-20T14:00:00",
        "OutboundArrivalDate": "2024-03-21T04:05:00",
        "OutboundDepartureAirportName": "Heathrow",
        "OutboundDepartureAirportCode": "LHR",
        "OutboundArrivalAirportName": "Abu Dhabi International",
        "OutboundArrivalAirportCode": "AUH",
        "OutboundLegCount": 1,
        "OutboundFlightDuration": 0,
        "OutboundFlightNumber": "MS778,MS916",
        "OutboundAirlineICAO": "MS",
        "InboundDepartureDate": "2024-03-22T05:05:00",
        "InboundArrivalDate": "2024-03-22T12:35:00",
        "InboundDepartureAirportName": "Abu Dhabi International",
        "InboundDepartureAirportCode": null,
        "InboundArrivalAirportName": "Heathrow",
        "InboundArrivalAirportCode": "LHR",
        "InboundLegCount": 1,
        "InboundFlightDuration": 0,
        "InboundFlightNumber": "MS917,MS777",
        "InboundAirlineICAO": "MS",
        "HolidayTypes": null,
        "Discount": null,
        "DiscountText": null,
        "CoupleRating": 0.0,
        "FamilyRating": 0.0,
        "TripAdvisorId": 0,
        "Resort": null,
        "HotelUrl": null,
        "HotelRating": null,
        "PostalCode": null,
        "CityName": null,
        "Latitude": null,
        "Longitude": null,
        "TripAdvisorRating": 0.0,
        "FreeCancellation": false,
        "HotelDescription": null,
        "Zoom": 0,
        "PayDeposit": false,
        "FromAirports": null,
        "Adult": null,
        "Child": null,
        "DateMin": null,
        "DateMax": null,
        "Duration": null,
        "BoardBasis": null,
        "SocialLinks": null
    },
    {
        "HotelKey": "7830025",
        "HotelName": null,
        "Image": null,
        "Countries": null,
        "Destination": null,
        "Amenities": null,
        "Location": null,
        "Price": 1104.0,
        "Rating": "5",
        "BoardTypeId": "8",
        "BoardTypeCode": "1",
        "QuoteRef": null,
        "OutboundFlightDirect": "false",
        "InboundFlightDirect": "false",
        "OutboundDepartureDate": "2024-03-20T14:05:00",
        "OutboundArrivalDate": "2024-03-21T03:55:00",
        "OutboundDepartureAirportName": "London Gatwick Airport",
        "OutboundDepartureAirportCode": "LGW",
        "OutboundArrivalAirportName": "Abu Dhabi International",
        "OutboundArrivalAirportCode": "AUH",
        "OutboundLegCount": 1,
        "OutboundFlightDuration": 0,
        "OutboundFlightNumber": "QR5942,QR1040",
        "OutboundAirlineICAO": "BA,QR",
        "InboundDepartureDate": "2024-03-22T05:25:00",
        "InboundArrivalDate": "2024-03-22T12:35:00",
        "InboundDepartureAirportName": "Abu Dhabi International",
        "InboundDepartureAirportCode": null,
        "InboundArrivalAirportName": "London Gatwick Airport",
        "InboundArrivalAirportCode": "LGW",
        "InboundLegCount": 1,
        "InboundFlightDuration": 0,
        "InboundFlightNumber": "QR1041,QR327",
        "InboundAirlineICAO": "QR",
        "HolidayTypes": null,
        "Discount": null,
        "DiscountText": null,
        "CoupleRating": 0.0,
        "FamilyRating": 0.0,
        "TripAdvisorId": 0,
        "Resort": null,
        "HotelUrl": null,
        "HotelRating": null,
        "PostalCode": null,
        "CityName": null,
        "Latitude": null,
        "Longitude": null,
        "TripAdvisorRating": 0.0,
        "FreeCancellation": false,
        "HotelDescription": null,
        "Zoom": 0,
        "PayDeposit": false,
        "FromAirports": null,
        "Adult": null,
        "Child": null,
        "DateMin": null,
        "DateMax": null,
        "Duration": null,
        "BoardBasis": null,
        "SocialLinks": null
    }]


    const groupedArray = array.reduce((acc, current) => {
        const key = current.HotelKey;
        if (!acc[key]) {
            acc[key] = [];
        }
        acc[key].push(current);
        return acc;
    }, {});
    
    const reducedArray = {};
    for (const key in groupedArray) {
        const lowestPriceHotel = groupedArray[key].reduce((min, current) => min.Price < current.Price ? min : current);
        reducedArray[key] = [lowestPriceHotel];
    }
    console.log(Object.values(reducedArray).flatMap(value => value));
    

    